### ISSUE TITLE
not compatible with create-react-app pkg

### ISSUE THREAD

**Issue by duanduan2015** [hengyang-zhao/unix-home#6]
$ npm install -g create-react-app
$ create-react-app my-app 
error msg
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1149
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1149:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:496:3

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/duanduan/test/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1149
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1149:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:496:3

**Comment by hengyang-zhao** [comment]
Not reproduced on my environment (Fedora 26). Please provide platform info.

**Comment by hengyang-zhao** [comment]
Actually it's a problem in npm implementation. It inherits bash umask unconditionally and thereafter creates files that have access issues for non-root users. Adjusted default bash umask to be 022 so that npm can work as expected.
