### ISSUE TITLE
How to remapping shortcuts

### ISSUE THREAD

**Issue by Lebo-Wang** [hengyang-zhao/unix-home#8]
att. Thx
e.g. Tmux shortcut change to 'Crtl + b'?

**Comment by psythefirst** [comment]
> 
> 
> att. Thx e.g. Tmux shortcut change to 'Crtl + b'?

https://github.com/hengyang-zhao/unix-home/blob/eb82ad616b0456157c537fbc13ee2105472250af/dot_files/tmux.conf#L1-L2

**Comment by Lebo-Wang** [comment]
> > att. Thx e.g. Tmux shortcut change to 'Crtl + b'?
> 
> https://github.com/hengyang-zhao/unix-home/blob/eb82ad616b0456157c537fbc13ee2105472250af/dot_files/tmux.conf#L1-L2

Good to know. Thx
